# Name of the Spring Boot application
# Used mainly for identification and logging
spring.application.name=ecombazaarx

# Port number where the Spring Boot server will run
# Access your app using: http://localhost:9090
server.port=9090

# DATABASE (MySQL) CONFIGURATION
# JDBC URL to connect Spring Boot with MySQL
# Format: jdbc:mysql://host:port/database_name
spring.datasource.url=jdbc:mysql://localhost:3306/ecombazaarx

# MySQL username (root in your case)
spring.datasource.username=root

# MySQL password
spring.datasource.password=Keerthana@mysql04\#

# JPA / HIBERNATE CONFIGURATION
# Automatically creates / updates tables based on Entity classes
# update = create tables if not exist, don't delete existing data
spring.jpa.hibernate.ddl-auto=update

# Shows SQL queries in the console (useful for debugging)
spring.jpa.show-sql=true

# Tells Hibernate which SQL dialect to use for MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
